### ISSUE TITLE
Cannot see firmware information

### ISSUE THREAD

**Issue by giovi321** [StyraHem/ShellyForHASS#102]
Running Home Assistant 0.102.1 on hassbian.
I cannot see firmware information for any shelly device in the lovelace frontend.
I used the following code for monstercard:
```
card:
  show_header_toggle: false
  title: Shelly status
  type: entities
filter:
  include:
    - entity_id: '*shelly*'
type: 'custom:monster-card'
```

What am I doing wrong?

**Comment by hakana** [comment]
Do you have additional_information enabled ? Do you have restricted login enabled on your device, you also have to specify user and password in shelly config.

**Comment by giovi321** [comment]
@hakana thank you for your reply.
In lovelace config or in home-assistant (configuration.yaml)?

**Comment by hakana** [comment]
Shelly section in config.yaml, see readme for the ShellyForHass component.

**Comment by giovi321** [comment]
I do have the following config in my configuration.yaml:
```
shelly:
  discovery: true
  sensors:
    - all
  additional_information: true
  upgrade_switch: true
```
I can see all options for the shelly but firmware upgrade.
