### ISSUE TITLE
0.1.5 Renames entity to "name" + "shelly ID"

### ISSUE THREAD

**Issue by elmigbot** [StyraHem/ShellyForHASS#117]
Hi, great component!

The latest update renamed all my shelly 1 switches as the title suggests. Example:

```
- id: XXXXXX
      name: "Office"
      light_switch: true
```
Appears as "Office XXXXXX" in HASS.

Thanks

**Comment by elmigbot** [comment]
This occurs even when discovery is set to false.

**Comment by hakana** [comment]
Do you have this flag enabled, show_id_in_name ?

**Comment by elmigbot** [comment]
No, it looks like this:

```
shelly:
  discovery: false
  devices:
    - id: 9XXXXX
      name: "Master Toilet"
      light_switch: true
```
