### ISSUE TITLE
Cloud device not discovered

### ISSUE THREAD

**Issue by LordBoos** [StyraHem/ShellyForHASS#122]
Only my local devices get discovered (3 shelly plug s). However my remote shelly plug s (not in my local network) connected to the cloud is not discovered even when manually adding it's shelly ID to the config. I can control the device using web and mobile app.

I have cloud key and server set up and there are no errors in the HA log.

```
shelly:
  cloud_auth_key: !secret shelly_cloud_auth_key
  cloud_server: !secret shelly_cloud_server
  discovery: true
  devices:
    - id: "XXXXXX"
      light_switch: true
```
