### ISSUE TITLE
No temperature sensor in HA for the  Shelly 2.5

### ISSUE THREAD

**Issue by luckyzor** [StyraHem/ShellyForHASS#130]
Hello, first wanted to say thank you for your effort to improve HA integrations :)

I have HACS and integrated my Shelly's very well.
I have only one probleme with the temperature sensor of my shelly 2.5: 
I can't see it in HA.

![image](https://user-images.githubusercontent.com/31155573/71475198-7b6aab80-27df-11ea-8766-2d1c7efe2612.png)

The consumption works very well.

thanks for your help

**Comment by hakana** [comment]
How is your config look like?

**Comment by hakana** [comment]
Should be fixed in 0.1.6.b4

**Comment by chemelli74** [comment]
@luckyzor , works fine here with 0.1.6b6. Can you retest please ?

Simone

**Comment by luckyzor** [comment]
I still have the same issue with 0.1.6b6

**Comment by hakana** [comment]
@luckyzor How is the shelly part in config.yaml look like?

**Comment by luckyzor** [comment]
`shelly:
  devices:  #configure devices
    - id: E5A1EE-1
      light_switch: true
      name: "Living room side lights"
    - id: E5A1EE-2
      light_switch: true
      name: "Living room center lights"`

Only have this in my config

**Comment by hakana** [comment]
```
shelly:
  sensors:
     - device_temp
  devices:  #configure devices
    - id: E5A1EE-1
      light_switch: true
      name: "Living room side lights"
    - id: E5A1EE-2
      light_switch: true
      name: "Living room center lights"
```
