### ISSUE TITLE
Shelly 2.5 missing current_position sensor (when in cover mode)

### ISSUE THREAD

**Issue by Erates** [StyraHem/ShellyForHASS#143]
I have a couple of Shelly 2.5 which are set up in cover mode.

But none of those publish a `sensor.shelly_shsw_25_xxxxxx_current_possition_attr` sensor. 

Could this be added please? Thanks!

**Comment by vistalba** [comment]
I just realized that today too.

**Comment by hakana** [comment]
You can do that by adding a template sensor.

Maybe we add this, on the same time I try to avoid this component to be too complex.

**Comment by Erates** [comment]
> You can do that by adding a template sensor.
> 
> Maybe we add this, on the same time I try to avoid this component to be too complex.

How do I do this? I've tried 
```yaml
shelly:
  discovery: true
  scan_interval: 5
  sensors:
    - all
  devices:
    - id: "xxxxxx"
      sensors:
        - current_position
        - device_temp
```

But that only gives an error stating 'current_position' is invalid.
