### ISSUE TITLE
Door/Window sensor is not represented correctly

### ISSUE THREAD

**Issue by astrandb** [StyraHem/ShellyForHASS#147]
I just received a couple of Door/Window sensors. Tested with 1.6.beta5 and latest firmware 1.5.7.
They work partially with HA but need a few fixes:
1  the main device should be a binary sensor with device class 'door' with options to configure as 'garage door' or 'window'. Now it is represented as a sensor which is not optimal.
2 the secondary device should be a sensor with device class 'illuminance', now it is displaying the lux value as temperature, e.g. 1824 C !
3 There is an attribute showing temperature when it should be lux value. And lux is already there as an attribute. Slightly confusing...

**Comment by chemelli74** [comment]
@astrandb , can you be so kind to post a screenshot and your confioguration.yaml ?

Thank you,

Simone

**Comment by morph027** [comment]
Similar here....looking at the config, this might be related to my list of sensors. Will try without it.

![Screenshot from 2020-01-21 11-31-08](https://user-images.githubusercontent.com/600106/72797524-8fb89180-3c41-11ea-88a0-d7a50d464ccc.png)

```
shelly:
  username: !secret shelly_user
  password: !secret shelly_password
  sensors:
    - power
    - rssi
    - device_temp
```
