### ISSUE TITLE
Slow update of lovelace card (CoAP not working)

### ISSUE THREAD

**Issue by fpalinf** [StyraHem/ShellyForHASS#158]
Hello,

With all the shelly switch I use (light, 2.5, led) when I switch on or off the shelly actually switches but the update of the visual indication on lovelace takes sometimes 1 minute.

I would be happy to provide debug log if of any help.

**Comment by chemelli74** [comment]
@fpalinf , please report back which version of the plugin you are using and attach the debug log. Also take a screenshot of the device details in lovelace (the card that open when you click on it).

Thank you,

Simone

**Comment by fpalinf** [comment]
Plugin version: 0.1.5 (the newest in HACS)
Where can I find the debug logs ?

It actually always update but it is not instantenously.
All card using a shelly updates together at the same time regardless when they were activated. 
It seems like a batch update. 

Object linked with MQTT or  - platform: flux_led update instantenously.

<img width="359" alt="Screenshot 2020-01-21 at 09 58 42" src="https://user-images.githubusercontent.com/19511928/72790105-38142900-3c35-11ea-8b0c-a7998aba3e16.png">

**Comment by chemelli74** [comment]
Hi,

I see you did a discovery by IP-address.
Would be possible to do a automatic discovery using CoAP ?
IIRC this is the only way to get istantaneous update, otherwise update is a polling every 60 seconds.

To actrivate debug log you have to add those lines to configuration.yaml:

```
logger:                                                                                                                                                                                                     
  default: warn                                                                                                                                                                                             
  logs:                                                                                                                                                                                                     
      **pyShelly: debug**                                                                                                                                                                                       

```
Log file is "home-assistant.log" in your config folder
               
Simone
