### ISSUE TITLE
Adding Shelly to Scenes

### ISSUE THREAD

**Issue by filmgarage** [StyraHem/ShellyForHASS#159]
When adding a shelly to a scene all settings of the shelly get included like wifi info, uptime etc.

It should only save the changeable settings of the device like 'state'.
Is it possible to facilitate this through the plugin? Or does the HA system need to be changed for this to be saved correctly?

Currently it gets saved like this:
```
- id: '1576804584936'
  name: Shelly Switch
  entities:
    light.shelly_switch:
      cloud_connected: true
      cloud_enabled: true
      cloud_status: connected
      discovery: CoAP-discovery
      firmware_version: 20191216-090109/v1.5.7@c30657ba
      friendly_name: Shelly Switch
      has_firmware_update: false
      icon: mdi:door
      ip_address: 192.168.66.130
      latest_fw_version: 20191216-090109/v1.5.7@c30657ba
      mqtt_connected: false
      rssi: -42
      shelly_id: '123456'
      shelly_type: Shelly 1
      ssid: 'MyWifi'
      state: 'on'
      supported_features: 0
      switch: 2
      uptime: 770018
```

Correctly would be:
```
- id: '1576804584936'
  name: Shelly Switch
  entities:
    light.shelly_switch:
      state: 'on'
```
