### ISSUE TITLE
Sensor data

### ISSUE THREAD

**Issue by mariobarisic** [StyraHem/ShellyForHASS#176]
I'm trying to get information's from shelly dimmer regarding brightness level but I could not manage do this!
I'm using sensor templating inside sensor.yaml configuration... 
What is the right way, or it is even possible to get brightness level? I can see that when light.shelly_shdm_1_ID is on first attribute brightness is available as value from 1  - 255.
I'm running latest ShellyForHASS 1.6.0. and I have configured only under configuration.yaml:
```
shelly:
  cloud_auth_key: !secret shelly_auth_key
  cloud_server: !secret shelly_server
  username: !secret shelly_user 
  password: !secret shelly_pass
```
so auto discovery is active and two types of shelly devices are available under HA (switch and dimmer).

**Comment by hakana** [comment]
What if you click on the dimmer?

![image](https://user-images.githubusercontent.com/1168654/73931080-f98a9980-48d7-11ea-9cbd-cfd2127c1f46.png)

**Comment by mariobarisic** [comment]
Dimming is working as expected and I can control the brightness of the light connected to the shelly dimmer, but I'm trying to get information as maybe sensor data what is the actual brightness value? I can see in HA -> Developer Tools -> States:
![image](https://user-images.githubusercontent.com/60128241/73931371-7b7ac280-48d8-11ea-9a16-bbd35620af6f.png)
or
![image](https://user-images.githubusercontent.com/60128241/73931415-8e8d9280-48d8-11ea-8e6d-d9c48e90b3b4.png)
that currently brightness is 137 or (137/255 * 100 = 54%) but how to extract this information to use for example in some script or automation...

**Comment by mariobarisic** [comment]
OK, i've managed to get brightness value for shelly dimmer switch getting the attribute value:

```
- platform: template
  sensors:
    brightness:
      friendly_name: "Shelly Dimmer brightness"
      value_template: "{{ state_attr('light.shelly_shdm_1_db3e78', 'brightness') }}"
```
so we can close this issue.
