### ISSUE TITLE
Shelly 1PM switch showing on/off state even it is unavailable

### ISSUE THREAD

**Issue by koooop** [StyraHem/ShellyForHASS#193]
Hi,

I have couple of Shelly 1PM switches added via ShellyForHASS. Problem is that they are constantly showing last on/off state even they are unplugged for several minutes and so should be unavailable. I would expect them to become unavailable in a minute after I disconnect them (I do not override unavailable_after_sec setting). They were discovered using CoAP and there is nothing special in my configuration:
```yaml
 shelly:
  sensors:
    - device_temp
    - current_consumption
    - total_consumption
```
Any idea what is wrong? I need to rely on correct unavailable status since I will be running these on low tariff outlets with regular daily outages.

Thanks for help!
