### ISSUE TITLE
Shelly H&T shows humidity as 2x actual reading

### ISSUE THREAD

**Issue by peter-ciccolo** [StyraHem/ShellyForHASS#201]
e.g., if it shows 50.5% in the app, the reported value in HA is 101

<img width="370" alt="Screen Shot 2020-02-23 at 2 22 36 PM" src="https://user-images.githubusercontent.com/47834747/75121420-a8550680-5648-11ea-8f1a-1704a7a94ccf.png">

**Comment by chemelli74** [comment]
Can you please check CoAP message using debug log ?
Thank you,

Simone

**Comment by peter-ciccolo** [comment]
Hi @chemelli74 , I don't see any relevant logs at `debug` or above. Am I missing something? Here is my logger config at the moment:

```
logger:
  default: critical
  logs:
    custom_components.shelly: debug
    shelly: debug
```
