### ISSUE TITLE
[FR] Option to convert to kWh and uptime seconds in days/hours/minutes/seconds

### ISSUE THREAD

**Issue by catalinbordan** [StyraHem/ShellyForHASS#232]
It would be nice for me if we can have the possibility to convert Wh to kWh. Then I can use the sensor  as source to power utility integrations. Right now I use rest sensor to get it in kWh, but it can give me errors in logs when the Shelly have issues in network.
Example of rest sensor.
  - platform: rest
    resource: http://192.168.0.84/status
    name: Laptop Power
    value_template: '{{ "%.0f"%(value_json.meters[0]["power"]) | float }}'
    scan_interval: 5
    unit_of_measurement: "W"
    device_class: power
    force_update: false
    timeout: 60

  - platform: rest
    resource: http://192.168.0.84/status
    name: Laptop kWh
    value_template: '{{ "%.4f"%((value_json.meters[0]["total"] / 60000) | float) | float }}'
    scan_interval: 120
    unit_of_measurement: "kWh"
    device_class: power
    force_update: true
    timeout: 60

I also want to check if some shelly have problems with wifi and restart. So I check uptime. but it is in seconds and it is hard to observe/convert in days,hours.minutes,seconds to compare between them.

**Comment by chemelli74** [comment]
You don't need to use rest, just do the math with the sensor provided by this plugin.

Simone

**Comment by chemelli74** [comment]
> I also want to check if some shelly have problems with wifi and restart. So I check uptime. but it is in seconds and it is hard to observe/convert in days,hours.minutes,seconds to compare between them.

Uptime is reset at every reboot.
If you want to monitor, here my automation:

```
  alias: Shelly uptime
  trigger:
    platform: event
    event_type: state_changed
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "
        {% set list = namespace(id=[]) %}
        {% for s in states.sensor %}
          {% if s.object_id.startswith('shelly_sh') and s.object_id.endswith('_uptime_attr') %}
            {% set list.id = list.id + [ s.entity_id ] %}
          {% endif %}
        {% endfor %}
        {{ trigger.event.data.entity_id in list.id }}"
      - condition: template
        value_template: "{{ trigger.event.data.new_state.state | int < 100 }}"
  action:
  - data_template:
      message: Shelly {{trigger.event.data.new_state.name}} restarted; uptime is {{trigger.event.data.new_state.state}}
      title: HA Notification - Shelly uptime
    service: notify.mail_send
  - data_template:
      message: Shelly {{trigger.event.data.new_state.name}} restarted; uptime is {{trigger.event.data.new_state.state}}
    service: system_log.write
```

Be aware that I have a config for "notify.mail_send" in order to receive a mail.

Simone
