### ISSUE TITLE
[Question] Expose cover position

### ISSUE THREAD

**Issue by sagoweb** [StyraHem/ShellyForHASS#27]
Thanks for the great work!
Is there a way to expose a cover position as a sensor?
Thank you!

**Comment by hakana** [comment]
The position is exposed as an attribute on the object and you can have it as an sensor by using a template sensor:

https://www.home-assistant.io/components/template/

```yaml
sensors:
  - platform: template
    sensors:
      my_pos:
        friendly_name: "My pos"
        unit_of_measurement: '%'
        value_template: "{{ state_attr('cover.shelly_shsw_21_xxxxxx', 'current_position') }}"
```
