### ISSUE TITLE
[FR] Improvement for "discovery_by_ip"

### ISSUE THREAD

**Issue by sstefanowski** [StyraHem/ShellyForHASS#270]
This is Feature Request.

I have currently two Wifi networks - two routers paired in WISP mode. As result there are two subnets with different addressing. My Shellies are using "Wifi Backup" option to connect on another router once primary is down. They also get the different IP when switching to the other router.
Due to my network architecture I'm using "discovery_by_ip" option - in config I have two devices but 4 IPs defined. 

Here is my config:
```
shelly:
#  discovery: true  
#  igmp_fix: true
  discover_by_ip:
    - '192.168.0.50'
    - '192.168.1.50'
    - '192.168.0.51'
    - '192.168.1.51'
  sensors:
    - all 
  devices:
    - id: "B8EXXX"
      light_switch: true
    - id: "C42XXX"
      light_switch: true
```

In case of fallback to backup Wifi the HA is not recognizing that Shelly device changed it's IP it becomes unavailable in HA (Shelly is still accessible in network - Web interface is accessible but under different IP). Then, when HA is restarted the plugin correctly discovers the Shelly under second IP.
It would be nice if after getting to "unavailable" the plugin could retry all of the IPs again trying to figure out if any Shelly changed its IP.
