### ISSUE TITLE
Lost current_consumption as Attribute for (Shelly 2) after upgrading to (ShellyForHASS v0.1.7)

### ISSUE THREAD

**Issue by DMQ8** [StyraHem/ShellyForHASS#273]
Hi,

Using latest Stable HA (108.6) and ShellyForHASS (v0.1.7) and latest Shelly 2 (fw v1.6.0).

After upgrading to ShellyForHASS (v0.1.7), "current_consumption" (W) as attribute are no more showing for (Shelly 2).  "current_consumption" is enabled as global setting under section "attributes:". 

Also not showing as current_consumption sensor for (Shelly 2), "current_consumption" is enabled as global setting under section "sensors:"

With Shelly 2.5 (fw v1.6.0), Shelly 1 PM (fw v1.6.1) & Shelly 4 Pro (fw v1.5.7) they are not effected and its still showing current_consumption as attribute and also as current_consumption sensor, with no issue.

Thanks.

**Comment by chemelli74** [comment]
Seems a bug, but unfortunately I cannot confirm as I don't own any Shelly 2.

Simone

**Comment by DMQ8** [comment]
Rolling back to ShellyForHASS v0.1.6, I can confirm that its showing in that release with no issue. So v0.1.7 seems to have this bug with Shelly 2.

**Comment by hakana** [comment]
How is your config look like? Have you specified all or current_consumption under attributes?

**Comment by DMQ8** [comment]
The following is my example, using global settings for sensors and attributes, with each shelly device specified with it's id:

```
shelly:
  settings:
     current_consumption: { decimals: 2 }
     total_consumption: { decimals: 2 }
     temperature: { decimals: 1 }  

  discovery: false
  version: false
  id_prefix: ''
  additional_information: true

  sensors: 
    - current_consumption
    - total_consumption
    - rssi
    - battery
    - switch
    - voltage
    - current
    - power_factor

  attributes:
    - ip_address
    - shelly_type
    - shelly_id
    - current_consumption
    - total_consumption
    - rssi
    - uptime
    - device_temp
    - battery
    - switch
    - voltage
    - current
    - power_factor

  devices:
    - id: "XXXXXX-1"
      entity_id: Test_x1
      name: Test x1
      light_switch: true

    - id: "XXXXXX-2"
      entity_id: Test_x2
      name: Test x2
      light_switch: true
#etc...
```
