### ISSUE TITLE
[FR] add a way to tell if a Shelly Door/Window is a door or a window

### ISSUE THREAD

**Issue by tcarlsen** [StyraHem/ShellyForHASS#302]
As default all my Shelly Door/Window sensors comes in as door sensors (with door icon (open closed). It would be nice to be able to tell ShelleForHASS that thius is a window sensor and then use the window icons (open and closed)

**Comment by chemelli74** [comment]
Is this setting there in Shelly's app ?

Simone

**Comment by tcarlsen** [comment]
dont thing so. so i was think of something like 

```yaml
shelly:
  discovery: true
  devices:
    - id: '5s67as7'
    type: window
```
