### ISSUE TITLE
[FR] Sensor for shutter positions

### ISSUE THREAD

**Issue by NelsonFrancisco** [StyraHem/ShellyForHASS#317]
## Is your feature request related to a problem? Please describe.
I cannot get the shutters' positions

## Describe the solution you'd like
I would like to have a sensor to tell me the shutters' positions. So I could place a card in lovelace to see the position of the shutters.

The current "cover" entity only tell me if it is opened or closed. Not enough

## Describe alternatives you've considered

I tried to use the "cover" entity but it is not enough. It only tells me if it is opened or closed

## Additional context
For example: Would be nice to have a similar graphic with the history of the shutter's position.
![image](https://user-images.githubusercontent.com/31771519/83965017-98d09500-a8a8-11ea-85b3-1e0b6ce586be.png)

Or even this one
![image](https://user-images.githubusercontent.com/31771519/83965043-be5d9e80-a8a8-11ea-83d4-c97f5a4be974.png)

**Comment by chemelli74** [comment]
Hi, you have a attribute called "current_position".
See my screenshot:

![image](https://user-images.githubusercontent.com/57354320/83975138-75cad300-a8f2-11ea-8c82-c36ac189f220.png)

Simone

**Comment by hakana** [comment]
If you want it as a separate sensor you can do that with sensor template in HA.

**Comment by NelsonFrancisco** [comment]
Ok.
Please give me time to try this at home: I don't have access to my home installation through the web

**Comment by NelsonFrancisco** [comment]
Thank you both!
I've manged to create a sensor entity for the shutter position. It looks nice.

**Comment by NelsonFrancisco** [comment]
I'm reopening because I have an related issue

So, I built this sensor:
```yml
shelly_shsw_25_68c63af9619d_position:
  unit_of_measurement: "%"
  value_template: "{{ state_attr('cover.shelly_shsw_25_68c63af9619d', 'current_position') }}"
  entity_id:
    - cover.shelly_shsw_25_68c63af9619d
  device_class: battery
```

But it seems to be a problem: the sensor update isn't working quite as expected. I have to reload the UI several times so the correct percentage position is displayed.

Any thoughts?
