### ISSUE TITLE
[FR] Add detached button support for Shelly 1

### ISSUE THREAD

**Issue by tigers75** [StyraHem/ShellyForHASS#336]

**Comment by david-kalbermatten** [comment]
You can have a long press and double-, triple-, quadruple-, .... press already with the `shelly_switch_click` event.

With the this event, you can have more than just single and long press. Just keep in mind that the Shelly Button Enclosure is a momentary switch which means that it behaves like this:

> Press Button down --> Off to On
> Release Button --> On to Off

This means that clicking a momentary switch like this creates **two** clicks not just **one** (this is why in the yaml-example it uses 2 and 4 clicks for single and double click.

### Single & Multiple-Click
```yaml
automation:
  - alias: "Shelly turn off and then on quickly, any switch"
    trigger:
      platform: event
      event_type: shelly_switch_click
      event_data:
        click_cnt: 2
        state: True
  - alias: "Shelly single click (momentary) on a specific switch"
    trigger:
      platform: event
      event_type: shelly_switch_click
      event_data:
        entity_id: sensor.shelly_shsw_1_XXXXXX_switch
        click_cnt: 2        
  - alias: "Shelly double click (momentary) on a specific switch"
    trigger:
      platform: event
      event_type: shelly_switch_click
      event_data:
        entity_id: sensor.shelly_shsw_1_XXXXXX_switch
        click_cnt: 4 
```

### Long Press
```yaml
- id: 'shelly_long_press'
  alias: This is an example of a long press with Shelly 1
  trigger:
  - platform: state
    entity_id: binary_sensor.shelly_shsw_1_xxxxxxxxx_switch
    for: 00:00:02
    from: 'off'
    to: 'on'
  action:
  - service: switch.toggle
    entity_id: switch.generic_switch
```
