### ISSUE TITLE
[BUG] Shelly H&T temperature only in whole degree steps

### ISSUE THREAD

**Issue by bigboban** [StyraHem/ShellyForHASS#388]
## Environment

- ShellyForHASS release with the issue: 0.1.9
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 104.3.
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised/hassio

## Describe the bug

I use shelly H&T with usb power cover. Till now i use MQTT integration. Temp was/is with 2 decimals granularity. But with ShellyForHASS it has only whole degree granularity.

## Steps to Reproduce

MQTT config:
```
- platform: mqtt
  state_topic: "shellies/shellyht-XXXXXX/sensor/temperature"
  name: "koule_balkon_teplota"
  unit_of_measurement: "°C"
  force_update: true
```

ShellyForHASS config:
```
  - id: "XXXXXX"
    name: "Shelly koule balkon"
    entity_id: koule_balkon
```

## Expected behavior

I expect same temp. precision as on MQTT.

## Traceback/Error logs

```txt

```

**Comment by chemelli74** [comment]
Hi, please check carefully read.me for setting your config.

Simone

**Comment by david-kalbermatten** [comment]
You can change that in the config for shelly
```yaml
# shelly.conf

settings:
    temperature: { decimals: 1 } # <---- You want to set this
discovery: true
scan_interval: 2
sensors:
  - all
devices:
  - id: "XXXXXXXXXX"
    light_switch: true
```

**Comment by jjdave2002** [comment]
Hello, I am trying this since hours, but could not change the decimals, always on 0, what is wrong? Thank you

**Comment by david-kalbermatten** [comment]
@jjdave2002 I splitt up my `configuration.yaml` into multiple files (see [here](https://www.home-assistant.io/docs/configuration/splitting_configuration/) for more information) 

*Example with Shelly configured directly inside `configuration.yaml`*
```yaml
# configuration.yaml
shelly:
  settings:
    temperature: { decimals: 1 } # <---- You want to set this
  discovery: true
  scan_interval: 2
  sensors:
  - all
  devices:
  - id: "XXXXXXXXXX"
    light_switch: true
```
