### ISSUE TITLE
Q: RGBW2 - power sensor

### ISSUE THREAD

**Issue by genem2** [StyraHem/ShellyForHASS#39]
I just transitioned from MQTT to Cloud, and this component is working great. However, I'm not seeing a power sensor attribute for the RGBW2. 
Until I rebooted the RGBW2, I was still receiving MQTT publishes, so my manual sensor was working, but that's gone now.

Should I be expecting a power sensor for the RGBW2?

Thanks.

> {
  "brightness": 25,
  "hs_color": [
    44.918,
    71.765
  ],
  "rgb_color": [
    255,
    208,
    71
  ],
  "xy_color": [
    0.486,
    0.446
  ],
  "white_value": 53,
  "ip_address": "192.168.0.76",
  "shelly_type": "Shelly RGBW2",
  "shelly_id": "662674",
  "ssid": "GM2.4",
  "rssi": -47,
  "uptime": 237156,
  "has_firmware_update": false,
  "latest_fw_version": "20190711-084448/v1.5.0-hotfix4@3b4f7414",
  "firmware_version": "20190711-084448/v1.5.0-hotfix4@3b4f7414",
  "cloud_enabled": true,
  "cloud_connected": true,
  "mqtt_connected": false,
  "cloud_status": "connected",
  "friendly_name": "TV Backlight",
  "supported_features": 145
}

**Comment by hakana** [comment]
Still missing in latest fw update

**Comment by chemelli74** [comment]
@genem2 , did you upgrade to latest fw (v1.5.7) ? IS the issue fixed ?

Simone

**Comment by chemelli74** [comment]
Hi,

anyone with RGBW2 that can test using latest firmware ?
Thank you,

Simone

**Comment by genem2** [comment]
Sorry for the delay in responding.
I don't think they want to expose the power in Cloud mode.

```
effect_list:
  - 'Off'
  - Meteor shower
  - Gradual change
  - Flash
brightness: 0
hs_color:
  - 0
  - 0
rgb_color:
  - 255
  - 255
  - 255
xy_color:
  - 0.323
  - 0.329
white_value: 5
effect: 'Off'
ip_address: 192.168.0.76
shelly_type: Shelly RGBW2
shelly_id: '662674'
discovery: CoAP-message
ssid: GM2.4
rssi: -48
uptime: 3194791
has_firmware_update: false
latest_fw_version: 20191216-090536/v1.5.7@c30657ba
firmware_version: 20191216-090536/v1.5.7@c30657ba
cloud_enabled: true
cloud_connected: true
mqtt_connected: false
cloud_status: connected
friendly_name: TV Backlight
supported_features: 149
icon: 'mdi:spotlight'
```

**Comment by chemelli74** [comment]
Sorry, I don't have one to test myself.
Maybe Worth testing using latest firmware.

Simone

**Comment by chemelli74** [comment]
Please update to firmware 1.6.0 and to plugin 1.0.7b1 and recheck,

Simone

**Comment by genem2** [comment]
I updated the RGBW2 to 1.6.0.
Works fine outside of HA. (Alexa, App, Browser)
Updated HA with 1.0.7b1.  The device is no longer being found.
Added:
```
logger:
  default: error
  logs:
    homeassistant.components.shelly: debug
```
but nothing's in the log file after another restart.
Did I configure logging correctly?

**Comment by chemelli74** [comment]
> Did I configure logging correctly?

https://github.com/StyraHem/ShellyForHASS/wiki/FAQ4:-Enable-debug-log

Simone

**Comment by genem2** [comment]
Sorry I missed that.
There three lines are repeating in the log:

```
2020-03-09 17:11:15 DEBUG (Poll) [pyShelly] Sending CoAP discover UDP
2020-03-09 17:11:24 DEBUG (mDns) [pyShelly] IGMP fix
2020-03-09 17:11:24 DEBUG (CoAP) [pyShelly] IGMP fix
```

This is my config:

```
shelly:
  discovery: false  # Just use devices below
  additional_information: True
  version: false #add version sensor
  show_id_in_name: False
  power_decimals: 1
  igmp_fix: True
  sensors:
    - all
  devices:      #devices to be added
    - id: 662674    #shellyrgbw2-662674
      name: "TV Backlight"   #set friendly name
      sensors:
        - power

```

**Comment by hakana** [comment]
Power sensor will be added in 0.1.7.b2

**Comment by chemelli74** [comment]
Please update to latest beta (0.1.7.b2) and recheck.

Simone

**Comment by genem2** [comment]
The repeating log entries seen with 0.1.7.b1 are no longer there with 0.1.7.b2, thank you.

> Power sensor will be added in 0.1.7.b2


FYI: If a power sensor should be visible in the attributes, I'm not seeing it. (RGBW2)

**Comment by chemelli74** [comment]
> FYI: If a power sensor should be visible in the attributes, I'm not seeing it. (RGBW2)

Just to be sure, we are speaking about consumption (total, current) or something else ?

Simone

**Comment by genem2** [comment]
Maybe this is just something Shelly isn't supporting outside of MQTT mode, but back when I used the RGBW2 in MQTT mode (as opposed to using their cloud), Home Assistant had an attribute to show the current power being consumed. I've pretty much written it off, until 

@hakana mentioned [above](https://github.com/StyraHem/ShellyForHASS/issues/39#issuecomment-596856215) that a power sensor will be added in 0.1.7.b2

If that's not something that can be done with the RGBW2 and firmware 1.6.0, that's fine.

**Comment by chemelli74** [comment]
@genem2, was asking because you should find "total_consumption" and "current_consumption". I'm not aware of "power" sensor.

Please try changing the sensor name to one or both of the above and report back.

Simone

**Comment by genem2** [comment]
Thank you. I must not be keeping up with doc changes.

```
shelly:
  discovery: false  # Just use devices below
  additional_information: True
  version: false #add version sensor
  show_id_in_name: False
  power_decimals: 1
  igmp_fix: True
  sensors:
    - all
  devices:      #devices to be added
    - id: 662674    #shellyrgbw2-662674
      name: "TV Backlight"   #set friendly name
      sensors:
        - current_consumption
        - total_consumption
```

Provides these attributes:

```
effect_list: Off, Meteor shower, Gradual change, Flash
brightness: 0
hs_color: 0, 0
rgb_color: 255, 255, 255
xy_color: 0.323, 0.329
white_value: 5
effect: Off
shelly_type: Shelly RGBW2
shelly_id: 662674
ip_address: 192.168.0.76
protocols: CoAP-msg, poll
has_firmware_update: false
cloud_status: connected
switch: false
friendly_name: TV Backlight
supported_features: 149
icon: mdi:spotlight
```

**Comment by chemelli74** [comment]
"total_consumption" and "current_consumption" are 2 entities (sensor), not attributes.

Simone

**Comment by chemelli74** [comment]
@genem2, did you find the new entities ? Can we close this issue ?

Simone

**Comment by genem2** [comment]
> Can we close this issue ?

I'm fine with closing it; I have the current power consumption value so I'm ok with this. I appreciate you implementing this.

Just some notes for you if valuable:

**My config:**
```
shelly:
  discovery: false  # Just use devices below
  additional_information: True
  version: false #add version sensor
  show_id_in_name: False
  power_decimals: 1
  igmp_fix: True
  sensors:
    - all
  devices:      #devices to be added
    - id: 662674    #shellyrgbw2-662674
      name: "TV Backlight"   #set friendly name
      sensors:
        - current_consumption
        - total_consumption

```        
After restarting HA, and turning on this light, I'm just seeing tv_backlight_current_consumption.
![EntityList](https://user-images.githubusercontent.com/46231389/77253100-8d5cbe80-6c15-11ea-955a-3f38ba8915f2.png)

When I change sensors: to **-all**, I see:
```
binary_sensor.shelly_shrgbw2_662674_mqtt_connected_attr	off	     
binary_sensor.shelly_shrgbw2_662674_switch	        off	     
sensor.shelly_shrgbw2_662674_cloud_status_attr	        connected
sensor.shelly_shrgbw2_662674_current_consumption	0.2	     
sensor.shelly_shrgbw2_662674_rssi_attr	                -55	     
sensor.shelly_shrgbw2_662674_uptime_attr                1113049	 
```
No total_consumption, so others may ping you on that.
_(The current Firmware version of your Shelly device is 20200309-104453/v1.6.0@43056d58)_

**Wiki Notes:**
        
When I started with this configuration some time ago, and went by the example under 
**Without discovery - manually specify devices**
This section still reflects the use of -power:
```
shelly:
  discovery: false
      sensors: #overide global (all)
         - power
         - device_temp

```         
In the wiki section: **Attributes (0.1.6-)**
I'm guessing now that this section documents things with plug-in v0.1.6 and earlier? Maybe that section title could be relabelled: **Attributes (v0.1.6 and earlier)**

One again, thank you for the work on this. Use what you'd like from above. If you want to pursue this total_consumption sensor, I'd be glad to test for you, otherwise, I'm good.
