### ISSUE TITLE
1 shelly can't be found

### ISSUE THREAD

**Issue by Alfiegerner** [StyraHem/ShellyForHASS#43]
Hi, 

Thanks very much for your work on this.  I really like being able to see ip address, overtemp status and other attributes as part of the shellies.

I've sucessfully migrated 24 shellies over from mqtt, but there's one that can't be found. Here's my shelly config:

```
shelly:
   discovery: true
   version: true #add version sensor
   igmp_fix: true
   sensors: all
   devices:    
     - name: "Cupboard"
       id: BA28E5
       light_switch: true

``` 
And the same unit in mqtt config:

```
light:
  - platform: mqtt
    name: "Pantry"
    state_topic: "shellies/shelly1-BA28E5/relay/0"
    command_topic: "shellies/shelly1-BA28E5/relay/0/command"
    qos: 2
    payload_on: "on"
    payload_off: "off"
```
I've turned logging on full debug, and only trace of string BA28E5 is for mqtt nothing showing for shelly component.

Any idea? Funky unit? 

Thanks,

Alex
