### ISSUE TITLE
[FR] shelly 2.5 roller % widget/controller

### ISSUE THREAD

**Issue by avol-io** [StyraHem/ShellyForHASS#451]
It's possibile have roller % percent to use in widget and maybe change it from the widget? like it's possibile to do with light brightness ?
Or dinamic name (like: "kitchen roller 30%") with arrow/stop icons?

**Comment by quammy** [comment]
Do you mean something like this:
![image](https://user-images.githubusercontent.com/3137488/94174655-4094c180-fe9e-11ea-94db-2db93079025e.png)

**Comment by avol-io** [comment]
like the first one

**Comment by quammy** [comment]
The first one is a standard HA loavelace set of a cover entity. The second one is a simple HA service execution. Here is the lovelace code:

```
      - entity: cover.shelly_roller_boys
        name: Boys
        secondary_info: 'Poistion: [[ {entity}.attributes.current_position ]]'
        type: 'custom:secondaryinfo-entity-row'
      - action_name: Execute
        icon: 'mdi:window-open'
        name: ...Set 20%
        service: cover.set_cover_position
        service_data:
          entity_id: cover.shelly_roller_boys
          position: '20'
        type: call-service
```
