### ISSUE TITLE
[BUG] Shelly 2.5 roller unable to use is_position on a condition

### ISSUE THREAD

**Issue by enricozocca** [StyraHem/ShellyForHASS#458]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 0.115.6
- Operating environment (Home Assistant/Supervised/Docker/venv): Ubuntu Docker

## Describe the bug
I've tried to create an automation that, in case of bad weather, check roller position if is between 51% and 100% set position to 50% but seems that value **is_position** is not recognized. If I comment condition, automation works well

```yaml
- id: '1601662537281'
  alias: Gestisci Tapparelle con pioggia
  description: ''
  trigger:
  - platform: state
    entity_id: weather.casa
    to: rainy
  - platform: state
    entity_id: weather.casa
    to: lightning-rainy
  - platform: state
    entity_id: weather.casa
    to: lightning
  condition:
  - condition: sun
    after: sunrise
    before: sunset
  action:
  - condition: device
    device_id: ba0804fcfdbb11ea939831292ba98139
    domain: cover
    entity_id: cover.shelly_shsw_25_10bba7
    type: is_position
    above: 51
    below: 100
  - device_id: ba0804fcfdbb11ea939831292ba98139
    domain: cover
    entity_id: cover.shelly_shsw_25_10bba7
    type: set_position
    position: 50
  - device_id: cb25473f056c11ebb54ee70d7b06562a
    domain: cover
    entity_id: cover.shelly_shsw_25_f3ff1c
    type: set_position
    position: 50
  mode: single
```

## Traceback/Error logs

```txt

```
