### ISSUE TITLE
Upgrade to 0.2.0 / 0.2.1.beta.1 and 1.8.3 - shellyforhass.click and shelly_switch_click do not fire 

### ISSUE THREAD

**Issue by quammy** [StyraHem/ShellyForHASS#466]
## Environment

- ShellyForHASS release with the issue: 0.2.1.beta.1 (and happened the same with 0.2.0)
- Last working ShellyForHASS release (if known): 0.1.9
- Home Assistant Core release with the issue: Latest
- Operating environment (Home Assistant/Supervised/Docker/venv): Supervised

## Steps to Reproduce

I have many shelly 2.5 (some defined as rollers and some as switches) and many shelly 1.
They all worked correctly with FW 1.7.* and ShellyForHASS 1.9, but I had to implement my own double click using the shelly_switch_click event. It worked ok but not perfect.
I now decided to test latest version so I upgraded ShellyForHASS to 0.2.0 and one Roller to latest FW (1.8.3).

Testing in HA -> Developer -> Events: shellyforhass.click - nothing appears. Also with shelly_switch_click now nothing appears from the roller.

This is the config.yaml:
```
  username: !secret shelly_username
  password: !secret shelly_password
  discovery: false
  version: true  
  sensors: 
    - current_consumption
    - total_consumption
    - rssi
    - uptime
    - over_power
    - device_temp
    - over_temp
    - mqtt
    - switch
    - voltage
    - current
#    - cloud
#    - battery
#    - total_returned
#    - power_factor             
  devices:
    - id: "68C63AFA31A3"
      name: Shutter - Salon (small)
      entity_id: roller_salon_small 
```
(I'm writing here as I don't have facebook account)

## Traceback/Error logs

```txt

```
