### ISSUE TITLE
[BUG] Shelly switch 1 - failed to call service

### ISSUE THREAD

**Issue by p-m-x** [StyraHem/ShellyForHASS#476]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): -
- Home Assistant Core release with the issue: 0.117.4
- Operating environment (Home Assistant/Supervised/Docker/venv): Docker 19.03.13

## Describe the bug
After HA reboot a shelly is not recognizable and return failed to call service error. It exists on entity list.
Start working as should after couple hours but don't know why and when exactly.
Reboot shelly doesn't help
Configured in yaml as auto discovery but the the same issue exists while connected via MQTT
I tried with igmp_fix: true/false but no positive results
```
shelly:
  discovery: true
  igmp_fix: true
  sensors:
    - all
  discover_by_ip:
    - '192.168.0.104'
  devices:  
    - id: "244325"
      light_switch: true  
      name: Outdoor entry front light
```
## Steps to Reproduce
Add shelly, reboot HA and try to turn on/off

## Expected behavior
Should be usable after discovery time (default 60sec)

## Traceback/Error logs
2020-11-22 22:08:00 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.2946732408] 'switch.shelly_front_light'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 135, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 444, in entity_service_call
    entity_ids.remove(entity.entity_id)
KeyError: 'switch.shelly_front_light'

```txt

```
