### ISSUE TITLE
Problem with the sensor when restarting the router

### ISSUE THREAD

**Issue by SvetZitrka** [StyraHem/ShellyForHASS#478]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: 
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant

## Steps to Reproduce
I use Shelly 3EM to measure electricity consumption. Everything works well. I create a sensor that adds all 3 phases together.

Everything worked well until the router to which the Home Assistant is connected is restarted. We restarted the router twice in a row and in the measurement, significant deviations are visible and data is distorted. Deviations occurred exactly at the time of router restart.

It doesn't seem to do that when the router is restarted, because it is short. But when the whole router shuts down for a few minutes. Then the sensor temporarily reports 0 and this is a problem from the measurement point of view.

The code looks like this

```
sensor:
  - platform: template
    sensors:
      energy_consumption_total:
        friendly_name: Energy Consumption Total
        icon_template: mdi:flash
        unit_of_measurement: kWh
        value_template: "{{ states('sensor.shelly_shem_3_40f52001972c_1_total_consumption')|float + states('sensor.shelly_shem_3_40f52001972c_2_total_consumption')|float + states('sensor.shelly_shem_3_40f52001972c_3_total_consumption')|float}}"
```

## Screenshots
This is how the problem looks visually https://drive.google.com/file/d/1NpnTFiGrSAeCzm9EmkVW25a86n-aevRy/view?usp=sharing

## Traceback/Error logs

```txt

```
