### ISSUE TITLE
[BUG] Support Shelly 1L cannot be switched on/off

### ISSUE THREAD

**Issue by fabian-born** [StyraHem/ShellyForHASS#486]
## Environment

- ShellyForHASS release with the issue: 
- Last working ShellyForHASS release (if known): latest
- Home Assistant Core release with the issue: 0.118.3
- Operating environment (Home Assistant/Supervised/Docker/venv):  supervised

## Describe the bug

After adding the new Shelly 1L to my home-assistant configuration it didn't generate any "switch" entity. So switching on/off is not possible through HA.

I miss following entry like this (Output from Shelly1):
switch.shelly_shsw_1_xxxxxxxxxx | off | shelly_type: Shelly 1 <br>shelly_id: xxxxxxx <br>ip_address: 192.168.xx.yy <br>room: carport <br>protocols: CoAP-discovery, CoAP-msg, poll <br>uptime: 22 h <br>has_firmware_update: true <br>mqtt_connected: false <br>cloud_status: connected <br>switch: false <br>friendly_name: carport-light
-- | -- | --

## Traceback/Error logs

```txt

```

## Additional context

My configuration:
```yaml
cloud_auth_key: !secret shelly_key
cloud_server: !secret shelly_server
discovery: true  #add all devices (default)
sensors: #sensors to show, can be override on each device
  - all
```
