### ISSUE TITLE
Custom [BUG]

### ISSUE THREAD

**Issue by rousveiga** [StyraHem/ShellyForHASS#487]
## Environment

- ShellyForHASS release with the issue: 0.2.0
- Last working ShellyForHASS release (if known): 
- Home Assistant Core release with the issue: first seen in 117.6, updated to 118.4 and had the same issue
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant

## Describe the bug

I have a Shelly EM with the following configuration:

```yaml
shelly:
  #host_ip: 192.168.0.138
  discovery: false
  id_prefix: ""
  devices:
    # other devices
    - id: "F9594D"
      name: Horno
      entity_id: horno
      sensors: [ current_consumption, total_consumption, over_power, total_returned, voltage ]
```

With this configuration, I expected the resultant entity IDs to have the form `switch.horno`, `sensor.horno_current_consumption`, `sensor.horno_current_consumption_2`, `sensor.horno_total_consumption`, `sensor.horno_total_consumption_2`, and so on. 

However, only about half of them (namely, the switch, both `current_consumption`s, and `over_power`) have the custom name and entity ID. The other entities have a name and entity ID that looks like the auto-generated ones: `sensor.shem_f9594d_1_total_consumption`, `

## Steps to Reproduce

Add the previous snippet to the configuration. Restart Home Assistant. Check the entities in the Shelly EM device entry.

## Expected behavior

I expected all the generated entities to have entity IDs in the form `sensor.horno_current_consumption` and names in the form `Horno - Current consumption`. 

## Screenshots

This is the list of entities I get from the Shelly EM device. Note how they have names in the two different formats.

![image](https://user-images.githubusercontent.com/11377258/100435074-b2a3a580-309d-11eb-840e-ea0b732bb439.png)

These are the details of an entity that has its name and entity ID in the form that I expected.

![image](https://user-images.githubusercontent.com/11377258/100435199-e979bb80-309d-11eb-866a-ed8aa099c9d1.png)

These are the details of an entity whose name and entity ID look autogenerated.

![image](https://user-images.githubusercontent.com/11377258/100435379-2180fe80-309e-11eb-9dd4-a6c2a18f497a.png)

## Traceback/Error logs

I couldn't find any relevant logs.

```txt

```
