### ISSUE TITLE
New device on network adds additional sensors even with discovery off

### ISSUE THREAD

**Issue by inforsgit** [StyraHem/ShellyForHASS#50]
This issue caused some misleading behaviour (which originally caused me to open Issue #49 ). Although everything there is working properly, it still exposed what I believe is a slight bug.

My configuration.yaml is as follows:

```
shelly:
  discovery: false
  additional_information: true
  sensors:
    - all
  devices:
    - id:.....
```
i.e. Discovery is off and I have to manually add new devices.

With this configuration I had expected that adding a new Shelly device to the network (in this case a Shelly Plug S) would be completely invisible in Home Assistant until I specified it in the configuration.yaml. However, after configuring the device in the Shelly app, the following sensors (device ID replaced with fffff) appeared in the HA states:

- sensor.shelly_shplg_s_ffffff_rssi_attr
- sensor.shelly_shplg_s_ffffff_rssi_attr
- sensor.shelly_shplg_s_ffffff_rssi_attr
- sensor.shelly_shplg_s_ffffff_rssi_attr
