### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kirbo** [StyraHem/ShellyForHASS#517]
```yaml
cloud_auth_key: !secret shelly_cloud_auth_key
cloud_server: !secret shelly_cloud_server
username: !secret shelly_username
password: !secret shelly_password
host_ip: !secret host_ip
mqtt_port: !secret mqtt_port
discovery: true
version: true
upgrade_switch: true
additional_information: true
tmpl_name: Shelly
attributes:
  - all
sensors:
  - all
devices:
  - id: <retained>
    name: Datacorner
    entity_id: datacorner

```

I'm getting only 6 entities for my Shelly Plug S.
Am I missing something, shouldn't my configuration enable _all_ sensors for _all_ devices?

![image](https://user-images.githubusercontent.com/1077974/105483700-e6bcd080-5cb2-11eb-8f69-c38460fcc025.png)
![image](https://user-images.githubusercontent.com/1077974/105483766-ffc58180-5cb2-11eb-88ad-616f250f73b4.png)
