### ISSUE TITLE
[FR] Support for Shelly Motion

### ISSUE THREAD

**Issue by Ede711** [StyraHem/ShellyForHASS#523]
## Is your feature request related to a problem? Please describe.
  The new Shelly Motion has just been released. It would be great to use the device with shellyforhass. With its features it offers a lot of possibilities to create automations.

## Describe the solution you'd like
Various sensors and entities to be able to use all the new features offered such as motion and tamper detection or the adjustable sensitivity.

## Describe alternatives you've considered
Support via MQTT is offered. However, this is quite laborious.

**Comment by hakana** [comment]
Yes I will add it as soon we get the sensors that are on there way.

**Comment by unbreakmat** [comment]
Following, bought a lot of these!

**Comment by tensink** [comment]
I bought 2 of these. Would be great to have these to work with ShellyForHass.

**Comment by danielsmith89** [comment]
Looking forward to the update, got a bunch of these waiting to integrate into HA! Thanks.

**Comment by hakana** [comment]
Working on that. I'm out of coffee looking forward for your contribution!

**Comment by danielsmith89** [comment]
> Working on that. I'm out of coffee looking forward for your contribution!

Will gladly once released! :)

**Comment by tensink** [comment]
> Working on that. I'm out of coffee looking forward for your contribution!

I'm very happy to contribute once a fully working version has been deployed.

**Comment by unbreakmat** [comment]
@hakana you can count me in as a tester, if you want i will install the beta software of this for you ;)

**Comment by Klaas-** [comment]
you can have a look at how the other shelly integration added the motion sensor:
https://github.com/home-assistant-libs/aioshelly/pull/45/files
https://github.com/home-assistant/core/commit/687f90e164690cc3484cad25b825c1c32382393d#diff-00e7b043e737e799f93beea049eaa0badfcf6966b24e8116ababf85a0cd54a1c
https://github.com/home-assistant/core/commit/f771d8ff142a98a47eb25adf726e8771bf2bf36a#diff-00e7b043e737e799f93beea049eaa0badfcf6966b24e8116ababf85a0cd54a1c

**Comment by danielsmith89** [comment]
@hakana any update as to when even just a beta is available to try? Thanks.

**Comment by hakana** [comment]
I will try to release it today!

**Comment by unbreakmat** [comment]
for those who cant wait i currently call it to hassio with the following code:
```
sensor:
  - platform: mqtt
    #state_topic: "shellies/shellymotionsensor-[some letters and number]/status"
    #name: "MQTT MOTION DETECTOR"
    name: "Smotion Motion"
    state_topic: "shellies/shellymotionsensor-[some letters and number]/status"
    unit_of_measurement: " "
    value_template: "{{ value_json.motion }}"
  - platform: mqtt
    name: "sMotion Battery"
    state_topic: "shellies/shellymotionsensor-[some letters and number]/status"
    unit_of_measurement: "%"
    value_template: "{{ value_json.bat }}"
  - platform: mqtt
    name: "sMotion Lux"
    state_topic: "shellies/shellymotionsensor-[some letters and number]/status"
    unit_of_measurement: "lux"
    value_template: "{{ value_json.lux }}"
  - platform: mqtt
    name: "sMotion vibration"
    state_topic: "shellies/shellymotionsensor-[some letters and number]/status"
    unit_of_measurement: " "
    value_template: "{{ value_json.vibration }}"
```

the [some letters and number] can you find by enabling mqtt on the shelly and download mqtt client on your computer like mqtt fx and subscribe to everything, walk passed the sensor and you should se the massages appear

hope this helps ;)
