### ISSUE TITLE
Binary sensor for switch events not added

### ISSUE THREAD

**Issue by uspino2** [StyraHem/ShellyForHASS#54]
According to changelog, 0.18 adds binary sensors for switch actions. That would be a great addition for motion devices, switch reeds, etc. After installation, I see no binary sensors added. Switch actions can only trigger an event but they don't show up as sensors. Is there something I missing? Can I build a sensor that just shows the state of the switch (true/false)?

**Comment by hakana** [comment]
How is your shelly part look like in config.yaml?

**Comment by filmgarage** [comment]
This is a fantastic feature. Now I can toggle my IKEA bulbs with the wall switch connected to the shelly. The shelly can be set to 'detached mode'. No more switching of the relays... And no need to rewire the shelly! Thanks a lot!!!

For what it's worth: here is my setup @uspino2 

```
shelly:
  discovery: true
  username: !secret username
  password: !secret password
  devices:
    - id: A1B2C3
      light_switch: true
      name: Detached Switch
      sensors:
        - switch
```

Automation example:

```
- id: '<some_id_number>'
  alias: Capture toggle of detached Switch
  trigger:
  - entity_id: sensor.shelly_detached_switch
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: sensor.shelly_detached_switch
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.ikea_bulb_or_alike
    service: light.toggle
```

**Comment by hakana** [comment]
So you got it to work as I understand? You can also use event to have actions for double click etc if you need.

**Comment by filmgarage** [comment]
I had it running straightaway! Just thought @uspino2 might be helped with my setup.
I will look into the double click feature later... Thanks!

**Comment by hakana** [comment]
My mistake, I thought you was the same person that created the issue. Thanks for the input and feedback!

**Comment by uspino2** [comment]
Binary switch sensor finally showed up. There’s two things I did. First I changed the device ID to all capital letters (is the component case sensitive?). Then after a few restarts the sensor just showed up. My config, just in case:

```
shelly:
  discovery: true
  version: true 
  show_id_in_name: true
  id_prefix: ""
  additional_information: true
  devices:
    - id: 3A4CF2
      light_switch: true
      name: Lamp
      entity_id: "lamp"
      sensors: 
         - switch
```

And congrats on this component, makes everything so simple and reliable. Any plans to make it official?
