### ISSUE TITLE
[BUG] HA Beta: [discovery] is an invalid option for [shelly]

### ISSUE THREAD

**Issue by SeraphimSerapis** [StyraHem/ShellyForHASS#563]
## Environment

- ShellyForHASS release with the issue:  0.2.2
- Last working ShellyForHASS release (if known): -
- Home Assistant Core release with the issue: 2021.6.0b0
- Operating environment (Home Assistant/Supervised/Docker/venv):  Docker

## Describe the bug

My config validation displays the following issue for my yaml-based ShellyForHASS configuration:

`- Invalid config for [shelly]: [discovery] is an invalid option for [shelly]. Check: shelly->shelly->discovery. (See ?, line ?). `

The same configuration works fine in 2021.5.X

## Steps to Reproduce

I use the following configuration:
```
shelly:
  discovery: true
  version: true
  upgrade_switch: true
  sensors:
    - all
  devices:
    - id: !secret shelly_3em
      name: "3EM"
    - id: !secret shelly_gas
      name: "Basement Gas"
```

## Expected behavior

No error message.

## Traceback/Error logs

```txt
- Invalid config for [shelly]: [discovery] is an invalid option for [shelly]. Check: shelly->shelly->discovery. (See ?, line ?). 
```
