### ISSUE TITLE
[FR] Energy Dashboard intregration

### ISSUE THREAD

**Issue by Techwolf12** [StyraHem/ShellyForHASS#578]
## Is your feature request related to a problem? Please describe.

The Shelly `total_consumption` is not selectable/usable in the energy dashboard.
## Describe the solution you'd like

Setting the `total_consumption` state_class to `total_increasing` and the `device_class` to `energy` (Power should be real time power, not long term usage). Also add the `last_reset` for the dashboard to properly handle it, to epoch time 0 since it doesn't need to be updated anyway.

## Describe alternatives you've considered

A alternative that could be used is to set this snippet in the configuration.yaml:
```
homeassistant:
  customize_glob:
      sensor.shelly_*_total_consumption:
        last_reset: '1970-01-01T00:00:00+00:00'
        state_class: total_increasing
        device_class: energy
```
This sets the attributes to the proper values for the Energy dashboard to handle it. But it would be nicer if it just worked for everyone without this change.

## Additional context

[Home Assistant dev docs on long term statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

**Comment by wonderiuy** [comment]
+1 for this request

**Comment by Octofinger** [comment]
+1 for this request.

I'd like to add the device_class _power_ and state_class _measurement_ for current consumption entities.

Just a note, I had to wrap the glob in quotes for the snippet to work in configuration.yaml.
```
homeassistant:
  customize_glob:
    "sensor.shelly_*_total_consumption":
    last_reset: '1970-01-01T00:00:00+00:00'
    state_class: total_increasing
    device_class: energy
```
