### ISSUE TITLE
entity_id not correctly applied

### ISSUE THREAD

**Issue by hk-ret** [StyraHem/ShellyForHASS#67]
hi @hakana this is a really excellent job you're doing.
I found a minor issue when using the entity_id option. Here is my configuration (extract):
```
sensors: [power,]
devices:
  - id: BA89D7-1
    name: Kellertreppe
    entity_id: basement
    sensors: [switch,power,]
  - id: BA89D7-2
    name: Waschküche
    entity_id: laundry
    light_switch: true
```

With this I ended up with the following entity-Ids (only the light has the correct entity Id):

- light.shelly_laundry
- sensor.shelly_shsw_25_ba89d7_1_consumption
- sensor.shelly_shsw_25_ba89d7_1_switch
- sensor.shelly_shsw_25_ba89d7_2_consumption
- switch.shelly_shsw_25_ba89d7_1
Only the light entity has the specified entity id. If I add an id prefix like this:
```
sensors: [power,]
id_prefix: Shelly
devices:
  - id: BA89D7-1
    name: Kellertreppe
    entity_id: basement
    sensors: [switch,power,]
  - id: BA89D7-2
    name: Waschküche
    entity_id: laundry
    light_switch: true

```
the entity-ids are correct:
- light.shelly_laundry_2
- sensor.shelly_basement_consumption
- sensor.shelly_basement_switch
- sensor.shelly_laundry_consumption
- switch.shelly_basement

Note: I've used Shelly (capitalized) as prefix, if I use shelly as prefix (lower case s) the result is the same as without prefix.

<Edit:> I've just noticed that I get an error when using the Shelly prefix together with the version sensor: `Invalid entity id: sensor.Shelly_version`

Cheers, Heinz
