### ISSUE TITLE
[new feature] Offset position for covers?

### ISSUE THREAD

**Issue by GoNzCiD** [StyraHem/ShellyForHASS#68]
It should be possible to include a offset percent for a cover to delete the % from the cover is closed to it start to go up?

I have implemented something related to this using the shelly API.  If I can I check out the code and try to understand it an the possibility to implent this as optional device parameter.

The idea is to know the % of shelly position correspond to the moment when the blind starts to go up. So this point should be the offset and the real 0% or 1% of the blind.

Thanks

**Comment by hakana** [comment]
Can you just save the current position in the automation and just compare it? In what way do you need this? I don't want to make this component to complex to understand.

**Comment by GoNzCiD** [comment]
Thanks for the dedication. I'm 100% aligned with the idea of make it easy to use, and this should be an optional configuration for those uses who wants more control/customization, like other device parameters (as `entity_id`).

Probably I didn't explain it well. This will be useful for blinds. It's more difficult to explain than understand.
- **What's the 'problem'?** The position value of the cover in shelly app doesn't match with the real blind position for a huge difference, at least in first 60 percent.
- **What's the root cause?** 
  - When the blind is totally closed shelly show 0%, right 
  - When the blind is totally openned shelly shows 100%, right
  - When the blind is in a position like [this image](https://ep00.epimg.net/elpais/imagenes/2017/06/15/fotorrelato/1497534373_962640_1497535020_album_normal.jpg) (A pic is better than try to explain it), the motor had made some turns and shelly show in cover position 20% (for instance). But I think it should be useful to take this position for cover as 1%, It's more real!
- **What I have been testing?** With the values of the expample in the previous point, I assume than the value for offset is the 20% (this value is configurable by device). So when Shelly show a position between 1 and 20, home assistant show a position of 1%. For shelly values over offset (20) apply a lineal value. This is an easy operaton than I have test in ha with a sensor to recover the position via rest:
```
- platform: rest
  name: "test_cover_position"
  scan_interval: 5
  resource: http://192.168.0.3/roller/0
  value_template: '{% set offset = 20 %}{% if value_json.current_pos == 0 %}0{%- elif value_json.current_pos <= offset -%}1{%- else -%}{{ ((100 * (value_json.current_pos - offset)) / (100 - offset))|int }}{%- endif %}'
  unit_of_measurement: "%"
  headers:
    content-type: application/x-www-form-urlencoded
    Authorization: !secret shelly_password
```
The reverse operation, when you send to shelly to be oppened in a concrete value, is the reverse calculation to send to the shelly device the correct value, this is a rest command to use with parameters `IP` and 'real' `position`:
```
shelly_cover_set_position:
  url: http://{{ip}}/roller/0
  method: POST
  headers:
    authorization: !secret shelly_password
    accept: 'application/json, text/html'
  payload: 'go=to_pos&roller_pos={% if position|int < 1 %}{{position}}{%- else -%}{{ position|int + ((100 - position|int) * offset|int / 100) }}{%- endif %} }}'
  content_type:  'application/x-www-form-urlencoded'
```
