### ISSUE TITLE
Does Shelly 2.5 work in detached mode?

### ISSUE THREAD

**Issue by RavenDK83** [StyraHem/ShellyForHASS#72]
Hi,
I have been trying to get a Shelly 2.5 working in detached mode with ShellyForHASS, but it seems like nothing is showing in Home Assistant. I can only see the relay as a switch, but not the input from the physical switch.

Is this supported?

Thanks.

**Comment by hakana** [comment]
You need to add the switch sensor in config to see the physical switches. You can configure this global or for each device. See also events in doc if you wan't to catch double clicks.

```yaml
shelly:
  discovery: true  #add all devices (default)
  sensors: #Global sensors for all devices (can be override for each device)
    - switch  #Enable physical switch status
  devices:
    - id: "123ABC"
      sensors: [ switch, power ]
```
