### ISSUE TITLE
[BUG] Shelly1 (v3) with auto off does not send state_change

### ISSUE THREAD

**Issue by mk-maddin** [StyraHem/ShellyForHASS#732]
## Environment

- ShellyForHASS release with the issue:  1.0.2
- Last working ShellyForHASS release (if known): unknown
- Home Assistant Core release with the issue: 2022.12.0
- Operating environment (Home Assistant/Supervised/Docker/venv): Home Assistant Supervised

## Describe the bug

I have configured a Shelly1 v3 (blue) with automatic off after 1 second (see screenshot below).
When the corresponding _switch.shelly_garage_cover2_ within home assistant is triggered 
OR when the shelly is triggered from the shelly iPhone App
OR when the shelly is triggered from the shelly integrated switch,
no "state_change" event is sent/fired within home assistant.

This issue happens as long as the integratin 'poll_interval' is lower than the automatic off setting.

## Steps to Reproduce

1. Set shelly1 to automatic turn off after 1 second
2. Create a test automation wtihin Home Assistant:
```
automation:

  - id: test_automation
    alias: test_automation
    description: 'Any test automation'
    initial_state: true
    mode: parallel
    trigger:     
      - id: 'state_change'
        platform: state
        entity_id: switch.shelly_garage_cover2
        to: 'on'
      - id: 'event_fired'
        platform: event
        event_type: state_changed
        event_data:
          new_state:
            entity_id: switch.shelly_garage_cover2
            state: "on"
    action:         
      - service: system_log.write
        data_template:
          message: "Triggerd by: {{trigger.id}}"
          logger: homeassistant.components.automation.test_automation
          level: error
```
3. Turn on the shelly switch -> no log entry is written / automation is not triggered.

## Expected behavior

A 'state_change' event is sent as soon as the switch is turned on
OR 
a state change happens as soon as the switch is turned on.

## Screenshots

![IMG_0261](https://user-images.githubusercontent.com/46523240/206652943-3c115c17-18a1-45df-b023-19c2f57700d8.jpg)

## Traceback/Error logs

```txt

```
