### ISSUE TITLE
Shelly not discovering my devices

### ISSUE THREAD

**Issue by seaverd** [StyraHem/ShellyForHASS#78]
Does this work with home assistant for docker?  Reason I am asking is that I have installed this through HACs, added shelly to my configuration.yaml and I cannot get it to discover my Shelly 2.5 device.

Any suggestions on how to troubleshoot this?

**Comment by GoNzCiD** [comment]
I have ha in docker, but I don't use discover. I put manually the devices I want to use with this component.
Check if your LAN setup blocks the connection or if you create the container with network mode in host.

**Comment by seaverd** [comment]
So good point....my home assistant docker was not in host mode....so I've
changed that.    By manual, do you mean adding the device to the Shelly
section of the configuration.yaml?  Still not getting discovery.  I have
nodered configured and toggling the device based on motion.   Would this
impact discovery since mqtt is being used on this device? Here is my config:

shelly:
  discovery: true
  sensors:
    - all #show all sensors
  devices:
    - id: "0084AF"
      light_switch: true

**Comment by GoNzCiD** [comment]
Yes @seaverd, y had it configured with `discovery: false` and I list each id on `devices` collection.
I have been tested yesterday after reading you and I can check than if I connect the shelly to another WLAN (guest wlan with intranet access) this shelly connector don't load the entities. But If I use rest_command with the ip, ha can view the shelly.
I don't know if it's a limitation of UDP blockage packages between this WLAN or where is the problem...

```yml
discovery: false
version: false 
username: !secret shelly_username
password: !secret shelly_userpassword
id_prefix: ''
additional_information: false
power_decimals: 2
sensors:
  - power
devices:
  - entity_id: garage
    id: 009A7C-1
    name: 'Main lights'
    light_switch: true
  - id: 009A7C-2
...
```
