### ISSUE TITLE
Shelly2,5  roller percentage

### ISSUE THREAD

**Issue by wifi75** [StyraHem/ShellyForHASS#88]
hello my confiuration it this:
```
shelly:
  discovery: false
  version: true #add version sensor
  sensors:
    - all
  devices:      #devices to be added
    - id: "E66E10"
    - id: "69214F"
    - id: "135474"
    - id: "5a444a"
    - id: "E67847"
    - id: "687e8d"
    - id: "6886c6"
       sensors: #overide global (all)
         - power
         - device_temp
```
How i can insert percentage in my card
